// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  jQuery(function() {
    var ListView, list_view;
    ListView = (function(_super) {
      __extends(ListView, _super);

      function ListView() {
        return ListView.__super__.constructor.apply(this, arguments);
      }

      ListView.prototype.el = $('body');

      ListView.prototype.initialize = function(param) {
        this.param = param;
        _.bindAll(this);
        return this.render();
      };

      ListView.prototype.render = function() {
        var a;
        a = "tatek";
        $(this.el).append('<ul><li>Hello, Backbone:' + this.param + '!</li></ul>');
        $(this.el).append("<ul><li>Hello, Backbone: " + a + "!</li></ul>");
        return alert("Backbone: " + a + " and " + this.param);
      };

      return ListView;

    })(Backbone.View);
    return list_view = new ListView("Konjek");
  });

  ({
    somefunc: function() {
      alert("ok this is doc load BB");
      $("body").append("<ul><li>Some text within li</li></ul>");
      $("body ul").append("<li>Some text added again in li</li>");
      return $("body ul").prepend("<li>Some text added in li FIRST</li>");
    }
  });

}).call(this);
