// Generated by CoffeeScript 1.7.1
(function() {
  window.ListView = Backbone.View.extend({
    el: "body",
    initialize: function() {
      alert("hiyak");
      _.bindAll(this);
      return this.render();
    },
    render: function() {
      var a;
      a = "tatek";
      $(this.el).append('<ul><li>Hello, Backbone:' + this.param + '!</li></ul>');
      $(this.el).append("<ul><li>Hello, Backbone: " + a + "!</li></ul>");
      return alert("Backbone: " + a + " and " + this.param);
    }
  });

  $(function() {
    var some_var;
    some_var = new ListView;
    return alert("hey!");
  });

  ({
    somefunc: function() {
      alert("ok this is doc load BB");
      $("body").append("<ul><li>Some text within li</li></ul>");
      $("body ul").append("<li>Some text added again in li</li>");
      return $("body ul").prepend("<li>Some text added in li FIRST</li>");
    }
  });

}).call(this);
